version: 0.2

phases:
  pre_build:
    commands:
      - echo Enter prebuild phase


  build:
    commands:
      - echo Build started
      - mvn clean package -DskipTests
      - dir target


  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - target/customer-service-0.0.1-SNAPSHOT.jar
  discard-paths: yes


