name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut koden
        uses: actions/checkout@v5

      - name: sätta upp java miljö
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Bygga och köra tester
        run: mvn -B package